### ISSUE TITLE
Visual direction

### ISSUE THREAD

**Issue by ricardoduplos** [developmentseed/doc-seed#17]
Here are two quick design comps showing the visual direction.

Style-wise, these follow the [DS.O](https://github.com/developmentseed/developmentseed.github.com) grammar refreshed by the changes introduced in [UI Seed](https://github.com/developmentseed/ui-seed). There are also some recognizable elements that come from our latest docs, like [OIN Proposal](https://docs.google.com/document/d/1hSvQzoLMllxA2QbFR5oNKoZMyFSfjv00fplLbqnGHOs/edit#heading=h.6adwhfqtcjlt) and [RRA Discovery Phase](https://docs.google.com/document/d/1iitYJsYXaCt1_2Uz3WKUApxW2-uVyMAbbUlvim23aXU/). Regarding the structure, I'm drawing inspiration from [Docbox](https://67-53007065-gh.circle-artifacts.com/0/tmp/circle-artifacts.NCC9T6a/index.html?language=cURL#our-api).

### A few notes

- Header contains title and optional subtitle (E.g. "Outcome Discovery Phase")
- Main nav can be divided into sections
- Main nav can contain submenu items
- Main nav / other "sidebar" contents are hidden by default on small screens. They are accessed via hamburger icon and displayed using an off-canvas pattern.

---

### On large screens

<img width="1440" alt="page-large 2x" src="https://user-images.githubusercontent.com/1016701/27802129-c8082764-6019-11e7-99e3-12486b3d6822.png">

---

### On small screens

<img width="320" alt="page-small 2x" src="https://user-images.githubusercontent.com/1016701/27802134-cd284c60-6019-11e7-8631-be9c41ce3bb1.png">

Thoughts?

CC @eliLitwack  @maxgrossman @olafveerman

**Comment by maxgrossman** [comment]
@ricardomestre 

From a design/writing style perspective, I really like this. I put those together because I think the sectioned design forces the reports to be very clear. That is we only talk about one thing in each section/subsection. Plus it allows figures or maps to be the focus of the page.

From a dev perspective:
- the subheader will fit easily with prose. 
- we'll have to add a few extra functions in [build-components](https://github.com/developmentseed/doc-seed/tree/develop/.build_scripts/build-components) to generate the sections/submenu items for the nav.
